language: node_js
node_js:
  - "node"
before_script:
  - npm run build
script:
  - npm run test
  - codecov -f coverage/*.json
jobs:
  include:
    - stage: release
    deploy:
      provider: script
      skip_cleanup: true
      script:
        - npx semantic-release